"""change items.title to non-nullable

Revision ID: 29495339f15c
Revises: eda70f402b62
Create Date: 2023-01-19 02:21:02.594668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29495339f15c'
down_revision = 'eda70f402b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
